version: '3.8'

services:
  signal-webhook:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SIGNAL_NUMBER=${SIGNAL_NUMBER}
      - SIGNAL_GROUP_ID=${SIGNAL_GROUP_ID}
      - WEBHOOK_API_KEY=${WEBHOOK_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./signal-data:/root/.local/share/signal-cli
    restart: unless-stopped